FROM alpine:latest

RUN mkdir -p /assignments
RUN mkdir -p /assignments/levelconfig

COPY prova1.json /assignments/
COPY prova2.json /assignments/
COPY prova3.json /assignments/
COPY levelConfig.json /assignments/levelconfig/
COPY badge_bronze.png /assignments/levelconfig/
COPY badge_silver.png /assignments/levelconfig/
COPY badge_gold.png /assignments/levelconfig/


