networks:
  testSmell-network:
    driver: bridge

services:
  userservice:
    image: mick0974/testsmellsgame:user_service
    container_name: user-service
    ports:
      - '8081:8081'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:./database/userdb
    networks:
      - testSmell-network

  compilerservice:
    image: mick0974/testsmellsgame:compiler_service
    container_name: compiler-service
    ports:
      - '8083:8083'
    networks:
      - testSmell-network

  leaderboardservice:
    image: mick0974/testsmellsgame:leaderboard_service
    container_name: leaderboard-service
    ports:
      - '8087:8087'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:./database/leaderboarddb
    networks:
      - testSmell-network

  exerciseservice:
    image: mick0974/testsmellsgame:exercise_service
    container_name: exercise-service
    ports:
      - '9090:9090'
    volumes:
      - assets:/usr/src/app/assets
    networks:
      - testSmell-network

  apigateway:
    image: mick0974/testsmellsgame:api_gateway
    container_name: api-gateway
    environment:
      - USER_SERVICE=http://user-service:8081
      - LEADERBOARD_SERVICE=http://leaderboard-service:8087
      - EXERCISE_SERVICE=http://exercise-service:9090
      - COMPILER_SERVICE=http://compiler-service:8083
    ports:
      - '9000:9000'
    networks:
      - testSmell-network

  frontend:
    image: mick0974/testsmellsgame:frontend
    container_name: frontend
    environment:
      - API_GATEWAY=http://api-gateway:9000
    ports:
      - '8080:8080'
    networks:
      - testSmell-network

volumes:
  assets:
    external: true


