FROM alpine:latest

RUN mkdir -p /assignments
RUN mkdir -p /assignments/levelconfig

COPY esperimento1.json /assignments/
COPY esperimento2.json /assignments/
COPY levelConfig.json /assignments/levelconfig/
COPY badge_bronze.png /assignments/levelconfig/
COPY badge_silver.png /assignments/levelconfig/
COPY badge_gold.png /assignments/levelconfig/


