FROM alpine:latest

RUN mkdir -p /assignments
RUN mkdir -p /levelconfig
RUN mkdir -p /levelconfig
RUN mkdir -p /badges
RUN mkdir -p /missions

COPY /assignments/*.json /assignments/

COPY /levelconfig/levelConfig.json /levelconfig/

COPY /badges/*.png /badges/

COPY /missions/*.json /missions/



